name: "CODEOWNERs Superpowers!"
description: "A simple way to turn your CODEOWNERs into superpowers!"
author: "Enderson Menezes <mail@enderson.dev>"

branding:
  icon: "command"
  color: "gray-dark"

inputs:
  super_power:
    description: "View the docs to see the superpowers available! (Default: require-all-codeowners)"
    required: true
    default: "require-all-codeowners"
  pr_number:
    description: "The PR number"
    required: true
  owner_and_repository:
    description: "The repository name"
    required: true
  gh-token:
    description: "The GitHub (Read the documentation to see how to create one)"
    required: true

# outputs:
#   is-ok:
#     description: "The action is OK?"
#     value: ${{ steps.boost-codeowners.outputs.is-ok }}

runs:
  using: "composite"
  steps:

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - shell: bash
      name: "Boost CODEOWNERs"
      id: boost-codeowners
      if: ${{ inputs.require_all_codeowners_at_line == 'true' }}
      run: main.sh ${{ inputs.owner_and_repository }} ${{ inputs.pr_number }} ${{ inputs.super_power }}
      env:
        GITHUB_TOKEN: ${{ inputs.gh-token }}